// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA02X5MDrhbzJO1luDIcpBY1SQBR-DTytE',
    appId: '1:785650598829:android:88aede2e2c25c859edd724',
    messagingSenderId: '785650598829',
    projectId: 'seg-badger-dev',
    storageBucket: 'seg-badger-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVb8NEjrUyx8Dh5adHdzfynzwt0vJq9ok',
    appId: '1:785650598829:ios:6fff7d061b1fb277edd724',
    messagingSenderId: '785650598829',
    projectId: 'seg-badger-dev',
    storageBucket: 'seg-badger-dev.appspot.com',
    androidClientId: '785650598829-mbn7pilmo1di5u9844ncuf1qacd4n446.apps.googleusercontent.com',
    iosClientId: '785650598829-eiji7atrbq6r5qmn5ttpb53tf5hnlgcg.apps.googleusercontent.com',
    iosBundleId: 'com.seg.badger',
  );
}
