# cd.yml
name: CD

on:
  push:
    branches:
      - "main"

jobs:
  # CI
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "12"
          distribution: "zulu"
      - name: Decrypt Android keys
        run: 7z x -o"./android" ./android/android-keys.7z -p"$GPG_PASSPHRASE"
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Install Flutter dependencies
        run: flutter pub get
        # Add build runner commands here if you have any
      - name: Format files
        run: flutter format --set-exit-if-changed .
      - name: Analyze files
        run: flutter analyze .
      - name: Run the tests
        run: flutter test
      - name: Build the APK
        run: flutter build apk --release
      - name: Upload artifact to Github
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk


# CD
  deploy_android:
    runs-on: ubuntu-latest
    needs: [build_android]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "12"
          distribution: "zulu"
      - name: Decrypt Android keys
        run: 7z x -o"./android" ./android/android-keys.7z -p"$GPG_PASSPHRASE"
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "master"
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build APK
        run: flutter build apk --release
      - name: Run Fastlane
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: android
